spring.application.name=peticle
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0

# Mysql 연결 설정
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/peticle
# spring.datasource.username=root
# spring.datasource.password=1209

# JPA 설정 (선택)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
